"""
Shared test setup.

create_app() refuses to build without a real SECRET_KEY (a deliberate
fail-fast so nobody boots the app with the placeholder from .env.example),
and the package lives at the repo root rather than on the default import
path. Both are fixed here so individual test modules can just
`from vcs import money`.

TWO KINDS OF TEST LIVE IN THIS DIRECTORY
----------------------------------------
1. **Pure tests** (`test_money.py`, `test_frontend.py`) — no database, no
   Docker, no running app. They exercise the money arithmetic, the input
   parsers and the stylesheet. These always run.

2. **Route tests** (`test_money_routes.py`) — a real Flask test client
   against a real Postgres, because the money *transactions* (checkout,
   billing, refunds) cannot be exercised any other way: they write rows,
   decrement stock and compute change in one request. They need a
   throwaway database and **skip cleanly when there isn't one**, so the
   fast suite stays runnable anywhere.

   To run them, bring up the isolated environment first:

       scripts/isolated_test_env.sh up jo

   then point the tests at it:

       TEST_DATABASE_URL=postgresql://postgres:test@localhost:55492/vetclinicsystem \\
         venv/bin/python -m pytest tests/ -q

   Never point TEST_DATABASE_URL at a real clinic database. These tests
   write and delete rows.
"""
import os
import sys
import pathlib

import pytest

REPO_ROOT = pathlib.Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT))

# Any non-placeholder value satisfies config.secret_key(). Set before import.
os.environ.setdefault("SECRET_KEY", "test-only-key-not-used-for-real-sessions")
# The in-process app's install identity, which licenses are signed for.
TEST_INSTALL_ID = "00000000-7e57-4000-8000-000000000001"
os.environ.setdefault("VETCLINICSYSTEM_INSTALL_ID", TEST_INSTALL_ID)

TEST_DB_URL = os.environ.get("TEST_DATABASE_URL")

# A safety interlock, not a formality. These tests write rows. If someone
# exports a real DATABASE_URL in their shell and runs pytest, we must not
# quietly reuse it — TEST_DATABASE_URL has to be set deliberately.
SKIP_REASON = (
    "no TEST_DATABASE_URL — route tests need a throwaway database. "
    "Run: scripts/isolated_test_env.sh up jo, then set "
    "TEST_DATABASE_URL=postgresql://postgres:test@localhost:55492/vetclinicsystem"
)

needs_db = pytest.mark.skipif(not TEST_DB_URL, reason=SKIP_REASON)


def _admin_id():
    """The seeded admin's id (scripts/isolated_test_env.sh creates it first,
    so 1 on a fresh database — but looked up, not assumed). None without a
    test database, where every test that would use it skips anyway."""
    if not TEST_DB_URL:
        return None
    try:
        import psycopg
        with psycopg.connect(TEST_DB_URL) as con:
            row = con.execute("SELECT id FROM users WHERE username='admin'").fetchone()
            return row[0] if row else None
    except Exception:
        return None


ADMIN_ID = _admin_id()


def new_id():
    """A record id for a test fixture that inserts rows directly. Far above
    anything an identity sequence reaches in a test database, so it never
    collides with a row the app itself creates (the columns are GENERATED BY
    DEFAULT, which accepts an explicit id without advancing the sequence)."""
    import random
    return random.randint(1_000_000_000, 2_000_000_000)


_APP = None


def _application():
    """The one application object of the session, built on first use."""
    global _APP
    if _APP is None:
        from vcs import create_app
        _APP = create_app()
        _APP.config.update(
            TESTING=True,
            # TESTING=True turns PROPAGATE_EXCEPTIONS on, which bypasses every
            # error handler the app registers — so a route that degrades
            # gracefully in production (flash + redirect) would surface here as a
            # raw 500. That is a configuration no clinic ever runs, and testing it
            # produces findings that are artefacts of the harness. Turn it back off
            # so these tests exercise the real error paths.
            PROPAGATE_EXCEPTIONS=False,
            # CSRF is verified separately by the app's own error handling; leaving
            # it on here would mean every test parsing a token out of HTML, which
            # tests Flask-WTF rather than the money logic.
            WTF_CSRF_ENABLED=False,
        )
    return _APP


@pytest.fixture(scope="session")
def bare_app():
    """The application object without a database, for a test of its
    configuration or templating that never reaches a table."""
    return _application()


@pytest.fixture(scope="session")
def flask_app():
    """The real application object, wired to the throwaway database."""
    if not TEST_DB_URL:
        pytest.skip(SKIP_REASON)
    os.environ["DATABASE_URL"] = TEST_DB_URL
    return _application()


@pytest.fixture(scope="session")
def client(flask_app):
    """Logged in as the seeded admin, who holds every permission."""
    c = flask_app.test_client()
    resp = c.post("/login", data={"username": "admin", "password": "Admin12345!"},
                  follow_redirects=True)
    assert resp.status_code == 200, "could not log in to the test database"
    with c.session_transaction() as sess:
        assert sess.get("user_id"), (
            "login did not establish a session — is the admin user seeded? "
            "scripts/isolated_test_env.sh up jo creates admin/Admin12345!")
    return c


@pytest.fixture
def db(flask_app):
    """A direct connection for arranging fixtures and asserting on stored
    rows — deliberately separate from the request-scoped pool the app uses,
    so a test reads what was actually committed rather than what a shared
    transaction is holding."""
    from vcs.db import pool as dbmod
    con = dbmod.connect()
    try:
        yield con
    finally:
        # A failed statement leaves Postgres refusing everything else on this
        # connection ("current transaction is aborted"). Rolling back before
        # close keeps one broken test from being reported as a broken fixture.
        try:
            con.rollback()
        except Exception:
            pass
        con.close()


# ---------------------------------------------------------------------------
# The money setting
# ---------------------------------------------------------------------------
# VetClinicSystem runs under a money setting, IQ or JO (money.py). Every test
# runs under one. A test (or its module, via `pytestmark`) marked
# `@pytest.mark.money("IQ")` or `("JO")` always runs under that setting: it
# asserts that setting's values. Every other test runs under the RUN's
# setting — the isolated environment's (TEST_DATABASE_URL on 55491 is iq,
# 55492 is jo), or VCS_TEST_MONEY=IQ|JO, or JO when neither says. That is
# what makes the two runs CLAUDE.md §5 asks for two different runs: until
# 2026-09-27 every unmarked test ran under JO in both, and the "iq" run
# repeated the "jo" run except for the tests marked IQ.
#
# The setting is made active in-process (money.set_current) for tests that
# call logic/money directly, AND written to the test database's settings
# table, because routes — through the test client or the live app the
# browser tests drive — read it from there on every request.
from vcs import money as _money
_stored_money_code = None
_ENV_PORTS = {"55491": "IQ", "55492": "JO"}


def run_money_code():
    """The money setting an unmarked test runs under in this run."""
    explicit = os.environ.get("VCS_TEST_MONEY", "").strip().upper()
    if explicit:
        if explicit not in _money.SETTINGS:
            raise pytest.UsageError(f"VCS_TEST_MONEY={explicit!r}: expected IQ or JO")
        return explicit
    port = (TEST_DB_URL or "").rsplit("@", 1)[-1].split("/", 1)[0].rsplit(":", 1)[-1]
    return _ENV_PORTS.get(port, "JO")


def pytest_configure(config):
    config.addinivalue_line(
        "markers", 'money(code): run this test under money setting "IQ" or "JO" '
                   "(unmarked: the run's setting, see run_money_code)")


@pytest.fixture(scope="session")
def vendor():
    """An ephemeral vendor signing key, trusted for this test process only
    (plan §14.4), and the vendor tool's own functions to mint tokens with it.
    Nothing here is written to disk, and the production launchers never
    trust a key at run time."""
    import types
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    sys.path.insert(0, str(REPO_ROOT / "scripts" / "vendor"))
    import vcs_vendor
    from vcs import config
    from vcs.licensing import tokens
    key = Ed25519PrivateKey.generate()
    public = vcs_vendor.public_bytes(key)
    tokens.trust_for_tests(vcs_vendor.kid_for(public), public)
    install_id = config.INSTALL_ID

    def license(install=None, **fields):
        from datetime import datetime, timedelta, timezone
        payload = vcs_vendor.license_payload(key, install or install_id, "Test Clinic",
                                             datetime.now(timezone.utc) + timedelta(days=365))
        payload.update(fields)
        return vcs_vendor.sign(key, payload)

    def dev_pass(install=None, hours=8, **fields):
        payload = vcs_vendor.pass_payload(key, install or install_id, "Test Developer", hours=hours)
        payload.update(fields)
        return vcs_vendor.sign(key, payload)

    return types.SimpleNamespace(key=key, tool=vcs_vendor, install_id=install_id,
                                 license=license, dev_pass=dev_pass)


@pytest.fixture
def developer(flask_app, vendor, monkeypatch):
    """A browser signed in to the Developer area with a valid pass, and to
    nothing else. Its sign-in counts against a limiter of its own: the
    limiter is shared with the clinic's sign-in, and the suite signs in often
    from one address."""
    from vcs.web import core
    monkeypatch.setattr(core, "_LOGIN_ATTEMPTS_BY_IP", {})
    c = flask_app.test_client()
    assert c.post("/developer/login", data={"dev_pass": vendor.dev_pass()}).status_code == 302
    return c


@pytest.fixture(scope="session", autouse=True)
def clinic_license(vendor, tmp_path_factory):
    """The in-process clinic's license (licensing plan §14.4): one year, in a
    license folder of its own, so no test writes into the checkout and no test
    runs read-only by accident. A test that changes the license puts this one
    back (tests/test_license.py)."""
    from vcs.licensing import state
    folder = tmp_path_factory.mktemp("license")
    mp = pytest.MonkeyPatch()
    mp.setattr(state, "license_dir", lambda: str(folder))
    (folder / "license.key").write_text(vendor.license() + "\n")
    state.refresh()
    yield folder
    mp.undo()


@pytest.fixture
def set_license(clinic_license, vendor):
    """set_license(expires_in_days, grace=14, warn=14): a key expiring that
    far from now (negative: already expired), stored and cached. The clinic's
    one-year key is put back afterwards."""
    from datetime import datetime, timedelta, timezone
    from vcs.licensing import state
    now = datetime.now(timezone.utc)
    key_file = clinic_license / "license.key"
    original = key_file.read_text()

    def _set(expires_in_days, grace=14, warn=14):
        payload = vendor.tool.license_payload(
            vendor.key, vendor.install_id, "Test Clinic", now + timedelta(days=expires_in_days),
            issued_at=now - timedelta(days=400), grace_days=grace, warn_days=warn)
        key_file.write_text(vendor.tool.sign(vendor.key, payload) + "\n")
        return state.refresh()

    yield _set
    key_file.write_text(original)
    state.refresh()


def pytest_report_header(config):
    return f"money setting for unmarked tests: {run_money_code()}"


def local_phone():
    """A mobile number as staff type it in the run's setting — the trunk 0,
    then the setting's local digits (9 in JO, 10 in IQ) — unique per call, so
    a test never meets a number already on file."""
    import uuid
    digits = _money.current().phone_local_length
    return "07" + str(uuid.uuid4().int)[:digits - 1].ljust(digits - 1, "0")


def amount(jo_value):
    """An amount written the way JO writes it, in the setting the test runs
    under: unchanged under JO, a thousand times larger under IQ ("12.000" is
    12,000 IQD).

    For a test about billing, refunds or reports rather than about one
    setting's arithmetic, so that it runs under both. Write values that are
    multiples of 0.250, results included: under IQ they are then whole
    250-dinar amounts, and nothing rounds."""
    from decimal import Decimal
    value = Decimal(str(jo_value))
    if _money.current().code == "IQ":
        value *= 1000
    return value.quantize(Decimal("0.001"))


def _store_money_setting(code):
    """Write the setting to the test database, skipping the round-trip when
    the previous test already left it at this value."""
    global _stored_money_code
    if not TEST_DB_URL or _stored_money_code == code:
        return
    import psycopg
    with psycopg.connect(TEST_DB_URL) as con:
        con.execute(
            "INSERT INTO settings (key, value) VALUES ('money_setting', %s) "
            "ON CONFLICT (key) DO UPDATE SET value = excluded.value", (code,))
        con.commit()
    _stored_money_code = code


def forget_stored_money_setting():
    """Call after a test changes the setting itself (e.g. through Settings),
    so the next test re-writes its own instead of trusting the cache."""
    global _stored_money_code
    _stored_money_code = None


@pytest.fixture(autouse=True)
def money_setting(request):
    marker = request.node.get_closest_marker("money")
    code = (marker.args[0] if marker else run_money_code()).upper()
    setting = _money.SETTINGS[code]
    _store_money_setting(code)
    token = _money.set_current(setting)
    # The clinic's clock follows the money setting's zone here (no test sets
    # the Time Zone setting unless it says so), exactly as a request would
    # resolve it. The `db` fixture connects after this, in the same zone.
    from vcs import clock as _clock
    clock_token = _clock.set_current(setting.timezone)
    try:
        yield setting
    finally:
        _clock.reset_current(clock_token)
        _money.reset_current(token)
