-- VetClinicSystem — migration 0001: the baseline schema (PostgreSQL).
--
-- The whole schema of the first release. Every later change is a new
-- numbered file beside this one; see schema.py for the rules. Until 1.0.0 is
-- published this file may be edited in place (no install has applied it).
--
-- Money: every amount is NUMERIC(15,3) — 12 digits before the point holds
-- the largest IQD amount, 3 after holds the fils — under BOTH money settings
-- (money.py). An IQ clinic's amounts are whole dinars stored as .000; a JO
-- clinic's use all three places. Quantities that are multiplied against a
-- price are NUMERIC(10,3), and percentages NUMERIC(5,2), so no arithmetic
-- ever mixes float and Decimal. Physical measurements (weight_kg), counts
-- never multiplied by a price (stock_counted, received_since_prior,
-- reorder_threshold, target_coverage_days, change_qty) are NUMERIC(10,3) too.
--
-- Time: business dates are DATE. Every event time is TIMESTAMPTZ, written
-- from clock.now() — the clinic's zone (clock.py) — and read back aware. A
-- request puts its session in that zone, so `::date` here and clock.today()
-- in Python name the same day.

CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);


-- History of nightly/manual database backups, shown in Settings.
CREATE TABLE backup_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('running','success','failed')),
    filepath TEXT,
    filesize_bytes BIGINT,
    error TEXT,
    triggered_by TEXT  -- 'manual' / 'nightly' / 'update' / 'shutdown' — NULL for older rows predating this column
);
CREATE INDEX idx_backup_log_started ON backup_log(started_at);

CREATE TABLE restore_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('success','failed')),
    source_file TEXT,
    error TEXT,
    triggered_by TEXT
);
CREATE INDEX idx_restore_log_started ON restore_log(started_at);


-- ============================================================ AUTH / USERS
CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    discount_cap INTEGER NOT NULL DEFAULT 0 CHECK (discount_cap BETWEEN 0 AND 100),
    -- Whether staff with this role can be assigned as the attending vet
    -- (Appointments grid, New Visit, Grooming, Inpatient) — a role
    -- attribute rather than a hardcoded role NAME check, so renaming or
    -- restructuring the "Vet" role can't silently empty every vet picker.
    is_vet_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL
);

-- Static seed list of every permission key the app understands — not
-- admin-editable itself, just the fixed vocabulary of what *can* be gated.
-- Kept in sync with auth.PERMISSIONS on every launch.
CREATE TABLE permissions (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    category TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE role_permissions (
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role_id INTEGER NOT NULL REFERENCES roles(id),
    custom_discount_cap INTEGER CHECK (custom_discount_cap BETWEEN 0 AND 100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
    -- Bumped every time this user's password_hash changes (self-service or
    -- admin reset). Stashed in the session at login and compared on every
    -- request (see require_login() in app.py) — a session logged in before
    -- the most recent change is invalidated, so a stolen cookie stops
    -- working the moment the password it was issued under is replaced,
    -- instead of staying valid for the rest of its normal lifetime.
    password_changed_at TIMESTAMPTZ,   -- NULL = never changed; a change signs out every other session
    created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_users_role ON users(role_id);

CREATE TABLE login_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    username TEXT,
    success INTEGER NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    ip TEXT,
    user_agent TEXT
);
-- The lockout check reads recent failures for one username on every login.
CREATE INDEX idx_login_user_ts ON login_log(username, timestamp);

CREATE TABLE audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    username TEXT,
    timestamp TIMESTAMPTZ NOT NULL,
    action TEXT NOT NULL,          -- 'create' / 'update' / 'delete'
    table_name TEXT NOT NULL,
    record_id TEXT NOT NULL,
    field TEXT,
    old_value TEXT,
    new_value TEXT
);
CREATE INDEX idx_audit_ts ON audit_log(timestamp);

-- ============================================================ OWNERS / PATIENTS
CREATE TABLE owners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    address TEXT,
    notes TEXT,
    -- Rewards card (features/REWARDS_CARD_PLAN.md). is_member and
    -- member_expires_on are deliberately separate facts: expiry never flips
    -- is_member, so "lapsed" stays distinguishable from "never joined".
    -- A card is active when is_member AND (member_expires_on IS NULL OR
    -- member_expires_on >= today) -- computed at read time through one
    -- helper, never by a background job that could stop running silently.
    is_member BOOLEAN NOT NULL DEFAULT FALSE,
    member_card_number TEXT,
    member_since DATE,
    -- NULL means the card never expires; the enroll form always pre-fills
    -- today + settings.member_term_months, so NULL only arises if someone
    -- clears the field on purpose.
    member_expires_on DATE,
    member_enrolled_by INTEGER REFERENCES users(id) ON DELETE RESTRICT
);
-- Nothing in the app looked up an existing owner by phone before
-- inserting a new one, so re-entering an existing owner's info (e.g. from
-- the "new patient" visit form) or double-submitting the new-owner form
-- silently created a duplicate row instead of failing or linking to the
-- existing owner. A plain UNIQUE index on a nullable column allows any
-- number of owners with no phone on file (each NULL is distinct in
-- Postgres) while rejecting a second owner with the same phone outright —
-- app.py's owner_new()/visit_new_patient() catch the resulting
-- IntegrityError and redirect to the existing owner instead of erroring.
CREATE UNIQUE INDEX idx_owners_phone_unique ON owners(phone) WHERE phone IS NOT NULL;
-- One card number, one owner. Partial, so any number of owners may hold
-- no card at all.
CREATE UNIQUE INDEX idx_owners_member_card ON owners(member_card_number)
    WHERE member_card_number IS NOT NULL;

CREATE TABLE patients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id INTEGER NOT NULL,
    animal_name TEXT,
    species TEXT,
    sex TEXT,
    age_note TEXT,
    repro_status TEXT,
    housing TEXT,
    notes TEXT,
    microchip TEXT,          -- optional; unique when present (index below)
    FOREIGN KEY (owner_id) REFERENCES owners(id)
);
CREATE INDEX idx_patients_owner ON patients(owner_id);
-- A plain unique index would make the column effectively single-valued
-- (every NULL distinct in Postgres, but every blank string equal), so it is
-- partial: any number of patients may have no chip on file, while a second
-- patient carrying a chip already recorded is rejected outright. app.py
-- checks first and catches the IntegrityError for the concurrent case.
CREATE UNIQUE INDEX idx_patients_microchip_unique ON patients(microchip)
    WHERE microchip IS NOT NULL;

-- ============================================================ DISTRIBUTORS / PRICE LIST / INVENTORY
CREATE TABLE distributors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    catalog_link TEXT,
    lead_time_days INTEGER,
    payment_terms TEXT,
    notes TEXT
);

-- Manual bookkeeping for what a distributor has billed you and what
-- you've paid them — a lump-sum charge per bill, payments recorded
-- against it, balance always computed (never stored). Not linked to
-- inventory, POS, or any report; every bill is a manual entry, same as
-- the paper/memory tracking this replaces.
CREATE TABLE distributor_bills (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distributor_id INTEGER NOT NULL,
    bill_date DATE NOT NULL,
    bill_reference TEXT,                 -- the distributor's own paper/invoice number, optional
    total_amount NUMERIC(15,3) NOT NULL CHECK (total_amount >= 0),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    created_by INTEGER,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (total_amount <> 'NaN')
);
CREATE INDEX idx_distbills_distributor ON distributor_bills(distributor_id);

CREATE TABLE distributor_bill_payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id INTEGER NOT NULL,
    amount NUMERIC(15,3) NOT NULL CHECK (amount > 0),
    payment_date DATE NOT NULL,
    method TEXT CHECK (method IN ('Cash','Card','Transfer')),   -- core.PAYMENT_METHODS; blank = not recorded
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    created_by INTEGER,
    FOREIGN KEY (bill_id) REFERENCES distributor_bills(id),
    FOREIGN KEY (created_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (amount <> 'NaN')
);
CREATE INDEX idx_distbillpayments_bill ON distributor_bill_payments(bill_id);

-- Price List is declared further down (after inventory_list) so its
-- linked_item_id FK can be inline, rather than a forward reference to a
-- table that doesn't exist yet in this file.

-- Inventory Catalog: Medical / Retail
CREATE TABLE inventory_list (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Medical' CHECK (category IN ('Medical','Retail')),
    unit TEXT,
    track_expiry BOOLEAN NOT NULL DEFAULT TRUE,
    cost_price NUMERIC(15,3),
    distributor_id INTEGER,
    -- 'Owned' (you bought this stock outright — the default) or
    -- 'Consignment' (a distributor's stock, sitting on your shelf; you
    -- owe them cost_price per unit only once it sells). Only meaningful
    -- for category='Retail' — enforced in app.py, not here. For a
    -- Consignment item, cost_price keeps its existing meaning (per-unit
    -- cost) but the *payee* changes: it's what's owed to distributor_id,
    -- not what the clinic itself paid — same column, same downstream
    -- COGS math, different real-world counterparty.
    ownership_type TEXT NOT NULL DEFAULT 'Owned' CHECK (ownership_type IN ('Owned','Consignment')),
    -- Set the moment this item most recently flipped Owned -> Consignment
    -- (app.py's consignment_items_bulk_edit). NULL if it's never been
    -- Consignment. consignment_balance() floors its sales/refund scan at
    -- this date per item, on top of the distributor-level period_start,
    -- so a sale from before the item was actually Consignment (e.g. years
    -- of prior Retail sales) never gets swept into what's owed.
    consignment_since TIMESTAMPTZ,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    barcode TEXT UNIQUE,
    -- Which of the two mutually-exclusive ways this item's barcode was set
    -- up: a real code entered/scanned in from the manufacturer's own
    -- packaging, or one this app generated internally. NULL alongside a
    -- NULL barcode when neither has ever been set up. Never both at once —
    -- enforced in app.py, not just here.
    barcode_source TEXT CHECK (barcode_source IN ('manual','generated')),
    notes TEXT,
    -- A Consignment item is by definition somebody's stock — the whole
    -- consignment layer (balance, overview, the receiving/shrinkage/
    -- returns pickers) inner-joins distributors, so an item in this state
    -- with no distributor silently disappears from all of it while still
    -- selling as consignment stock. See ORPHANED_RECORDS_AUDIT.md F-07.
    CONSTRAINT inventory_consignment_needs_distributor_ck
        CHECK (ownership_type <> 'Consignment' OR distributor_id IS NOT NULL),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (cost_price IS NULL OR (cost_price >= 0 AND cost_price <> 'NaN'))
);

-- Price List: Service / Medicine / Retail
-- Medicine billing lines are priced by range and do NOT touch inventory stock.
-- Only Retail rows (optionally linked to an inventory item) are sold via POS and move stock.
CREATE TABLE price_list (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Service' CHECK (category IN ('Service','Medicine','Retail')),
    cost_price NUMERIC(15,3),
    sale_price NUMERIC(15,3),
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    linked_item_id INTEGER,             -- Retail rows only: links to inventory_list.id for POS
    can_discount BOOLEAN NOT NULL DEFAULT FALSE,   -- if false, a bill containing this item can't have a discount applied
    FOREIGN KEY (linked_item_id) REFERENCES inventory_list(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (cost_price IS NULL OR (cost_price >= 0 AND cost_price <> 'NaN')),
    CHECK (sale_price IS NULL OR (sale_price >= 0 AND sale_price <> 'NaN'))
);

-- ============================================================ AUDITS (whole-catalog Save/Confirm sessions)
-- One session = one shelf-walk. "Not Started Yet" is simply the absence of a session
-- for a date; a session becomes 'Confirmed' (locked, can't be edited) the moment the
-- user presses Confirm, otherwise it stays 'Draft' ("Saved") and can be resumed/edited.
-- Only Confirmed sessions count toward Inventory Status / Ordering Sheet history.
CREATE TABLE audit_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date DATE NOT NULL,
    performed_by INTEGER,
    status TEXT NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Confirmed')),
    created_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,
    FOREIGN KEY (performed_by) REFERENCES users(id)
);

CREATE TABLE audit_session_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    stock_counted NUMERIC(10,3),
    received_since_prior NUMERIC(10,3) NOT NULL DEFAULT 0,
    reorder_threshold NUMERIC(10,3),             -- NULL = inherit from the last confirmed audit
    critical_item INTEGER,           -- NULL = inherit
    target_coverage_days NUMERIC(10,3),          -- NULL = inherit
    nearest_expiry_date DATE,
    notes TEXT,
    FOREIGN KEY (session_id) REFERENCES audit_sessions(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    -- Counts are physical quantities: never negative, never NaN. NaN is the
    -- one that matters -- it is not just bad data, it disables the guards
    -- that read it (SIMULATION_AUDIT_2026-09-11.md F2/F5). A plain `>= 0`
    -- would NOT catch it: Postgres sorts NaN above every number, so
    -- 'NaN' >= 0 is true. Infinity cannot be stored in NUMERIC(10,3) at all.
    CHECK (stock_counted IS NULL OR (stock_counted >= 0 AND stock_counted <> 'NaN')),
    CHECK (received_since_prior >= 0 AND received_since_prior <> 'NaN'),
    CHECK (reorder_threshold IS NULL OR (reorder_threshold >= 0 AND reorder_threshold <> 'NaN')),
    CHECK (target_coverage_days IS NULL OR (target_coverage_days >= 0 AND target_coverage_days <> 'NaN')),
    -- One line per item per session — lets _save_audit_lines() use a
    -- single INSERT ... ON CONFLICT DO UPDATE instead of a
    -- check-then-insert, closing the race where two concurrent saves for
    -- the same item could both insert.
    UNIQUE (session_id, item_id)
);
CREATE INDEX idx_auditlines_session ON audit_session_lines(session_id);
CREATE INDEX idx_auditlines_item ON audit_session_lines(item_id);

-- Real-time stock movement — ONLY from POS Retail sales (not Medicine billing).
CREATE TABLE inventory_transactions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    change_qty NUMERIC(10,3) NOT NULL CHECK (change_qty <> 'NaN'),
    reason TEXT NOT NULL,            -- 'sale' / 'manual_adjustment'
    ref_id TEXT,
    timestamp TIMESTAMPTZ NOT NULL,
    user_id INTEGER,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    -- See ORPHANED_RECORDS_AUDIT.md F-19 — 14 user-referencing columns
    -- across this schema had no FK; nothing dangles today (no delete-user
    -- route exists, deactivate only), but the protection was accidental.
    -- RESTRICT matches how both apps already behave.
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);
-- (item_id, timestamp): current stock is the last audit's count plus every
-- movement for that item after the audit's timestamp.
CREATE INDEX idx_invtxn_item_ts ON inventory_transactions(item_id, timestamp);

-- ============================================================ CONSIGNMENT
-- A distributor's stock sitting on your shelf — they're owed cost_price
-- per unit once it sells, you keep the markup. Consignment items are
-- ordinary Retail inventory_list rows (ownership_type='Consignment'), so
-- they already flow through pos_checkout / audit sessions / P&L exactly
-- like owned stock; these tables are the distributor-facing receiving/
-- shrinkage/returns/settlement layer on top of that shared data.
CREATE TABLE consignment_receipts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    distributor_id INTEGER NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_cost_at_receipt NUMERIC(15,3) NOT NULL,
    received_date DATE NOT NULL,
    delivery_reference TEXT,
    notes TEXT,
    received_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (received_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (quantity > 0 AND quantity <> 'NaN'),
    CHECK (unit_cost_at_receipt >= 0 AND unit_cost_at_receipt <> 'NaN')
);
CREATE INDEX idx_consreceipts_item ON consignment_receipts(item_id);
CREATE INDEX idx_consreceipts_distributor ON consignment_receipts(distributor_id);

CREATE TABLE consignment_shrinkage (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    distributor_id INTEGER NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('Damaged','Expired','Other')),
    liable_party TEXT NOT NULL CHECK (liable_party IN ('Distributor','Clinic')),
    liability_overridden BOOLEAN NOT NULL DEFAULT FALSE,
    unit_cost NUMERIC(15,3) NOT NULL,
    notes TEXT,
    logged_by INTEGER,
    logged_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (logged_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (quantity > 0 AND quantity <> 'NaN'),
    CHECK (unit_cost >= 0 AND unit_cost <> 'NaN')
);
CREATE INDEX idx_consshrinkage_item ON consignment_shrinkage(item_id);
CREATE INDEX idx_consshrinkage_distributor ON consignment_shrinkage(distributor_id);

CREATE TABLE consignment_returns (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id INTEGER NOT NULL,
    distributor_id INTEGER NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_cost_at_return NUMERIC(15,3) NOT NULL,
    return_date DATE NOT NULL,
    reason TEXT,
    notes TEXT,
    returned_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (returned_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (quantity > 0 AND quantity <> 'NaN'),
    CHECK (unit_cost_at_return >= 0 AND unit_cost_at_return <> 'NaN')
);
CREATE INDEX idx_consreturns_item ON consignment_returns(item_id);
CREATE INDEX idx_consreturns_distributor ON consignment_returns(distributor_id);

CREATE TABLE consignment_settlements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    distributor_id INTEGER NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    amount_owed NUMERIC(15,3) NOT NULL,
    amount_paid NUMERIC(15,3) NOT NULL,
    payment_method TEXT CHECK (payment_method IN ('Cash','Card','Transfer')),
    notes TEXT,
    settled_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (distributor_id) REFERENCES distributors(id),
    FOREIGN KEY (settled_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (amount_owed > 0 AND amount_owed <> 'NaN'),
    CHECK (amount_paid >= 0 AND amount_paid <> 'NaN'),
    CONSTRAINT settlements_paid_within_owed_ck CHECK (amount_paid <= amount_owed)
);
CREATE INDEX idx_conssettlements_distributor ON consignment_settlements(distributor_id);

-- ============================================================ VISITS (visit + wellness + grooming, one record)
CREATE TABLE visits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    visit_type TEXT,                  -- 'Outpatient' / 'Inpatient'
    date DATE,
    doctor TEXT,                      -- free text, populated from a Vet-user dropdown on new entries
    weight_kg NUMERIC(10,3) CHECK (weight_kg IS NULL OR (weight_kg >= 0 AND weight_kg <> 'NaN')),  -- kilograms, at this visit
    bcs INTEGER CHECK (bcs BETWEEN 1 AND 9),   -- Body Condition Score, 1-9 scale
    complaint TEXT,
    history TEXT,
    exam TEXT,
    treatment TEXT,
    case_status TEXT NOT NULL DEFAULT 'Needs Filling'
        CHECK (case_status IN ('Needs Filling','Ongoing','Admitted to Inpatient','Deceased/Euthanized',
                                'Lost to Follow Up','Resolved','Referred')),
    case_status_changed_at TIMESTAMPTZ,      -- drives the 2-week "Lost to Follow Up" missed-flag clock
    updates_log TEXT,

    -- Follow-up (method, not type)
    followup_needed TEXT,             -- 'Y' / 'N'
    followup_method TEXT,             -- 'Physical Visit' / 'Phone Call'
    followup_reason TEXT,
    followup_date DATE,
    followup_status TEXT,             -- 'Pending' / 'Completed' / 'Cancelled' / 'N/A'

    -- Wellness reminder
    wellness_needed TEXT DEFAULT 'N',
    wellness_type TEXT,                -- 'Annual Vaccine' / 'Rabies Vaccine' / 'Deworming' / 'Spot On/Pill'
    wellness_next_dose_date DATE,
    wellness_contacted TEXT DEFAULT 'N',
    wellness_contact_method TEXT,      -- 'Phone Call' / 'Message'

    -- Grooming
    grooming_needed TEXT DEFAULT 'N',
    grooming_services TEXT,            -- comma-separated service names
    grooming_notes TEXT,
    grooming_admitted_items TEXT,
    grooming_status TEXT,              -- 'Waiting' / 'Ongoing' / 'Finished'
    grooming_contacted TEXT DEFAULT 'N',

    payment_status TEXT,               -- derived/display cache; real status computed from payments
    created_by INTEGER,
    -- The edit-conflict token (routes/clinical.py edit_is_stale): set when
    -- the row is created and on every write to a column visit_edit()
    -- also writes, so an edit form opened before that write is refused
    -- instead of silently undoing it. Never NULL: a NULL once meant "nothing
    -- to compare", which left every record's first edit unguarded (audit B4).
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    -- See F-19.
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_visits_patient ON visits(patient_id);
CREATE INDEX idx_visits_date ON visits(date);
CREATE INDEX idx_visits_followup ON visits(followup_date);
CREATE INDEX idx_visits_wellness_due ON visits(wellness_next_dose_date);

-- Billing: Automatic (priced line items) OR Manual (single lump amount)
CREATE TABLE billing (
    visit_id INTEGER PRIMARY KEY,
    billing_type TEXT NOT NULL DEFAULT 'Automatic' CHECK (billing_type IN ('Automatic','Manual')),
    -- codes column removed — Automatic billing is driven entirely by
    -- visit_billing_lines (price_id + quantity rows), not a comma string.
    manual_amount NUMERIC(15,3),               -- Manual: single lump sum, exported as one "Veterinary Services" line
    date_billed DATE,
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount_applied_by INTEGER,
    -- Which kind of discount discount_percent holds. A member's rewards
    -- card and a staff discount share this one slot on purpose: every
    -- money reader already reads discount_percent, and a second column
    -- would be one more thing each of them could forget. A bill never
    -- carries both (the card is the only discount a member's bill can
    -- take), so one slot is enough. See features/REWARDS_CARD_PLAN.md A1.
    discount_source TEXT NOT NULL DEFAULT 'staff' CHECK (discount_source IN ('staff','member')),
    notes TEXT,
    -- The final payable figure for this bill (what compute_bill_totals()
    -- actually charges), kept in sync by logic.refresh_visit_billing_total()
    -- every time lines/discount/manual_amount change. Reports read this
    -- instead of re-deriving subtotal*(1-discount%) independently.
    total NUMERIC(15,3) NOT NULL DEFAULT 0,
    -- "Clean Up" — a capped, explicit staff write-off applied at payment
    -- time (see CLEANUP_FEATURE_PLAN.md). Cumulative running total ever
    -- forgiven on this bill.
    cleanup_amount NUMERIC(15,3) NOT NULL DEFAULT 0,
    cleanup_applied_by INTEGER,
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    -- See F-19.
    FOREIGN KEY (discount_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (cleanup_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (total >= 0 AND total <> 'NaN'),
    CHECK (manual_amount IS NULL OR (manual_amount >= 0 AND manual_amount <> 'NaN')),
    CHECK (cleanup_amount >= 0 AND cleanup_amount <> 'NaN'),
    CHECK (discount_percent BETWEEN 0 AND 100)
);

-- Automatic visit billing's line items, snapshotted at Save time (search-
-- and-add billing UI in visit_detail.html) — this is what stops a later
-- Price List edit from retroactively changing what an already-billed
-- visit's bill (or that month's revenue/COGS report) says today.
CREATE TABLE visit_billing_lines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id INTEGER NOT NULL,
    price_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    quantity NUMERIC(10,3) NOT NULL DEFAULT 1,
    unit_price NUMERIC(15,3) NOT NULL,
    unit_cost NUMERIC(15,3),
    created_at TIMESTAMPTZ NOT NULL,
    -- Was this line eligible for a discount when it was billed, copied
    -- from price_list.can_discount at insert. Snapshotted for the same
    -- reason unit_price is: can_discount can be edited at any time, and
    -- without the snapshot a later edit would silently change a past
    -- bill's total and misprice its refunds. NOT NULL with no default so
    -- a future insert site that forgets it fails loudly instead of
    -- silently marking a non-discountable item discountable.
    discountable BOOLEAN NOT NULL,
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (price_id) REFERENCES price_list(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (quantity > 0 AND quantity <> 'NaN'),
    CHECK (unit_price >= 0 AND unit_price <> 'NaN'),
    CHECK (unit_cost IS NULL OR (unit_cost >= 0 AND unit_cost <> 'NaN'))
);
CREATE INDEX idx_visitbillinglines_visit ON visit_billing_lines(visit_id);

-- payments is declared further down (after boarding_sessions/
-- inpatient_cases) so its FKs to both can be inline, rather than a
-- forward reference to a table that doesn't exist yet in this file.

-- ============================================================ BOARDING
-- Relies on the existing Patient/Owner records — a boarding session just
-- links to a patient_id, the same way a Visit or Inpatient case does.
CREATE TABLE boarding_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    entry_date DATE NOT NULL,
    dismissal_date DATE,              -- expected/actual end date; editable if the stay is extended or shortened
    admitted_items TEXT,
    special_needs BOOLEAN NOT NULL DEFAULT FALSE,   -- chronic disease or custom requirement flag
    special_needs_notes TEXT,
    room TEXT,
    price_per_day NUMERIC(15,3),
    total NUMERIC(15,3),           -- raw subtotal (price_per_day * nights, or entered manually)
    -- 1 when `total` was auto-suggested (the Total field was left blank at
    -- create/edit time) rather than typed explicitly. While the stay is
    -- still active and this is 1, boarding_billing_summary() recomputes the
    -- subtotal live from price_per_day x nights-so-far instead of trusting
    -- this stale snapshot — but only when it's still the auto-suggested
    -- figure, so a deliberately-typed custom total is never silently
    -- overwritten.
    total_is_auto BOOLEAN NOT NULL DEFAULT TRUE,
    -- The persisted figure boarding_page()'s batched list view and any
    -- report read instead of recomputing per row — kept in sync by
    -- logic.refresh_boarding_total() every time the session is saved.
    billed_total NUMERIC(15,3),
    -- "Clean Up" write-off — see the matching comment on billing.cleanup_amount.
    cleanup_amount NUMERIC(15,3) NOT NULL DEFAULT 0,
    cleanup_applied_by INTEGER,
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount_applied_by INTEGER,
    -- Which kind of discount discount_percent holds. A member's rewards
    -- card and a staff discount share this one slot on purpose: every
    -- money reader already reads discount_percent, and a second column
    -- would be one more thing each of them could forget. A bill never
    -- carries both (the card is the only discount a member's bill can
    -- take), so one slot is enough. See features/REWARDS_CARD_PLAN.md A1.
    discount_source TEXT NOT NULL DEFAULT 'staff' CHECK (discount_source IN ('staff','member')),
    dismissed BOOLEAN NOT NULL DEFAULT FALSE,   -- has the animal actually left yet
    created_by INTEGER,
    -- The edit-conflict token (routes/clinical.py edit_is_stale): set when
    -- the row is created and on every write to a column boarding_edit()
    -- also writes, so an edit form opened before that write is refused
    -- instead of silently undoing it. Never NULL: a NULL once meant "nothing
    -- to compare", which left every record's first edit unguarded (audit B4).
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    -- See F-19.
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (cleanup_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (discount_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (price_per_day IS NULL OR (price_per_day >= 0 AND price_per_day <> 'NaN')),
    CHECK (total IS NULL OR (total >= 0 AND total <> 'NaN')),
    CHECK (billed_total IS NULL OR (billed_total >= 0 AND billed_total <> 'NaN')),
    CHECK (cleanup_amount >= 0 AND cleanup_amount <> 'NaN'),
    CHECK (discount_percent BETWEEN 0 AND 100)
);
CREATE INDEX idx_boarding_patient ON boarding_sessions(patient_id);

-- "Something's Wrong!" incident log for a boarding stay
CREATE TABLE boarding_incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boarding_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    issue TEXT NOT NULL,
    contacted TEXT NOT NULL DEFAULT 'N',        -- 'Y' / 'N'
    contact_method TEXT,                        -- 'Phone Call' / 'Text Message'
    response TEXT,
    user_id INTEGER,
    FOREIGN KEY (boarding_id) REFERENCES boarding_sessions(id),
    -- See F-19.
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_boardingincidents_boarding ON boarding_incidents(boarding_id);

-- ============================================================ INPATIENT SYSTEM
CREATE TABLE inpatient_cases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    visit_id INTEGER,
    complaint TEXT,
    exam_findings TEXT,
    weight_kg NUMERIC(10,3) CHECK (weight_kg IS NULL OR (weight_kg >= 0 AND weight_kg <> 'NaN')),  -- kilograms, at admission
    bcs INTEGER CHECK (bcs BETWEEN 1 AND 9),   -- Body Condition Score, 1-9 scale
    admission_date DATE NOT NULL,
    admitted_items TEXT,
    dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    dismissal_date DATE,
    attending_vet_id INTEGER,
    supervising_vet_id INTEGER,
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount_applied_by INTEGER,
    -- Which kind of discount discount_percent holds. A member's rewards
    -- card and a staff discount share this one slot on purpose: every
    -- money reader already reads discount_percent, and a second column
    -- would be one more thing each of them could forget. A bill never
    -- carries both (the card is the only discount a member's bill can
    -- take), so one slot is enough. See features/REWARDS_CARD_PLAN.md A1.
    discount_source TEXT NOT NULL DEFAULT 'staff' CHECK (discount_source IN ('staff','member')),
    created_by INTEGER,
    -- The final payable figure for this case (what compute_bill_totals()
    -- actually charges), kept in sync by logic.refresh_inpatient_total()
    -- every time procedures/discount change.
    total NUMERIC(15,3) NOT NULL DEFAULT 0,
    -- "Clean Up" write-off — see the matching comment on billing.cleanup_amount.
    cleanup_amount NUMERIC(15,3) NOT NULL DEFAULT 0,
    cleanup_applied_by INTEGER,
    -- The edit-conflict token (routes/clinical.py edit_is_stale): set when
    -- the row is created and on every write to a column inpatient_edit()
    -- also writes, so an edit form opened before that write is refused
    -- instead of silently undoing it. Never NULL: a NULL once meant "nothing
    -- to compare", which left every record's first edit unguarded (audit B4).
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (attending_vet_id) REFERENCES users(id),
    FOREIGN KEY (supervising_vet_id) REFERENCES users(id),
    -- See F-19.
    FOREIGN KEY (discount_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (cleanup_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (total >= 0 AND total <> 'NaN'),
    CHECK (cleanup_amount >= 0 AND cleanup_amount <> 'NaN'),
    CHECK (discount_percent BETWEEN 0 AND 100)
);
CREATE INDEX idx_inpatient_patient ON inpatient_cases(patient_id);
CREATE INDEX idx_inpatient_visit ON inpatient_cases(visit_id);

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id INTEGER,
    inpatient_case_id INTEGER,
    boarding_id INTEGER,
    amount NUMERIC(15,3) NOT NULL,
    method TEXT CHECK (method IN ('Cash','Card','Transfer')),
    date DATE NOT NULL,
    user_id INTEGER,
    notes TEXT,
    -- Every payment belongs to exactly one of the three billable record
    -- types. All three columns are nullable so any one of them can be
    -- used; nothing previously stopped a row from using none of them,
    -- which cash_register_totals() would still have counted. See
    -- ORPHANED_RECORDS_AUDIT.md F-14.
    CONSTRAINT payments_one_anchor_ck CHECK (
        (visit_id IS NOT NULL)::int
      + (inpatient_case_id IS NOT NULL)::int
      + (boarding_id IS NOT NULL)::int = 1
    ),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (boarding_id) REFERENCES boarding_sessions(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (amount > 0 AND amount <> 'NaN')
);
CREATE INDEX idx_payments_visit ON payments(visit_id);
CREATE INDEX idx_payments_case ON payments(inpatient_case_id);
CREATE INDEX idx_payments_boarding ON payments(boarding_id);
CREATE INDEX idx_payments_date ON payments(date);

CREATE TABLE inpatient_updates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    note TEXT NOT NULL,
    user_id INTEGER,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id),
    -- See F-19.
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_inpupdates_case ON inpatient_updates(case_id);

CREATE TABLE inpatient_contact_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    picked_up INTEGER NOT NULL,
    staff_user_id INTEGER,
    notes TEXT,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id),
    -- See F-19.
    FOREIGN KEY (staff_user_id) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_inpcontact_case ON inpatient_contact_log(case_id);

CREATE TABLE inpatient_billing (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id INTEGER NOT NULL,
    price_id INTEGER NOT NULL,
    quantity NUMERIC(10,3) NOT NULL DEFAULT 1,
    -- Price/cost snapshotted at the moment this line was added — so a
    -- later Price List edit can't retroactively change what an
    -- already-billed stay owes, or this month's revenue/COGS report for
    -- an already-logged procedure. unit_cost stays nullable: not every
    -- price_list row necessarily has a cost_price set (Services
    -- typically don't carry a COGS basis).
    unit_price NUMERIC(15,3),
    unit_cost NUMERIC(15,3),
    logged_by INTEGER,
    timestamp TIMESTAMPTZ NOT NULL,
    -- Was this line eligible for a discount when it was billed, copied
    -- from price_list.can_discount at insert. Snapshotted for the same
    -- reason unit_price is: can_discount can be edited at any time, and
    -- without the snapshot a later edit would silently change a past
    -- bill's total and misprice its refunds. NOT NULL with no default so
    -- a future insert site that forgets it fails loudly instead of
    -- silently marking a non-discountable item discountable.
    discountable BOOLEAN NOT NULL,
    FOREIGN KEY (case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (price_id) REFERENCES price_list(id),
    -- See F-19.
    FOREIGN KEY (logged_by) REFERENCES users(id) ON DELETE RESTRICT,
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (quantity > 0 AND quantity <> 'NaN'),
    CHECK (unit_price IS NULL OR (unit_price >= 0 AND unit_price <> 'NaN')),
    CHECK (unit_cost IS NULL OR (unit_cost >= 0 AND unit_cost <> 'NaN'))
);
CREATE INDEX idx_inpbilling_case ON inpatient_billing(case_id);

-- ============================================================ FILE ATTACHMENTS
CREATE TABLE attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id INTEGER NOT NULL,
    visit_id INTEGER,
    inpatient_case_id INTEGER,
    relative_path TEXT NOT NULL,
    original_name TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL,
    uploaded_by INTEGER,
    -- list_attachments() only ever queries by visit_id OR
    -- inpatient_case_id, so a row with neither is invisible everywhere —
    -- and so is the clinical file it points at. See
    -- ORPHANED_RECORDS_AUDIT.md F-13.
    CONSTRAINT attachments_one_anchor_ck
        CHECK ((visit_id IS NOT NULL) <> (inpatient_case_id IS NOT NULL)),
    FOREIGN KEY (patient_id) REFERENCES patients(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (uploaded_by) REFERENCES users(id)
);
CREATE INDEX idx_attach_patient ON attachments(patient_id);
CREATE INDEX idx_attach_visit ON attachments(visit_id);
CREATE INDEX idx_attach_case ON attachments(inpatient_case_id);

-- ============================================================ POINT OF SALE (Retail only)
CREATE TABLE sales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sold_at TIMESTAMPTZ NOT NULL,    -- the moment of the sale, to the microsecond, so a sale in the same second as an audit confirmation does not tie under inventory_status()'s strict '>' comparison
    cashier_id INTEGER,
    subtotal NUMERIC(15,3) NOT NULL,
    discount_percent NUMERIC(5,2) NOT NULL DEFAULT 0,
    discount_applied_by INTEGER,
    -- Which kind of discount discount_percent holds. A member's rewards
    -- card and a staff discount share this one slot on purpose: every
    -- money reader already reads discount_percent, and a second column
    -- would be one more thing each of them could forget. A bill never
    -- carries both (the card is the only discount a member's bill can
    -- take), so one slot is enough. See features/REWARDS_CARD_PLAN.md A1.
    discount_source TEXT NOT NULL DEFAULT 'staff' CHECK (discount_source IN ('staff','member')),
    -- The customer this sale is attributed to, when staff identified one
    -- at checkout. NULL on an ordinary walk-in, which is the common case:
    -- selecting a customer is opt-in and nothing prompts for it.
    owner_id INTEGER REFERENCES owners(id) ON DELETE RESTRICT,
    total NUMERIC(15,3) NOT NULL,
    payment_method TEXT CHECK (payment_method IN ('Cash','Card','Transfer')),
    -- Cash payment method only — what the customer actually handed over
    -- and what was handed back, for the cashier's own reconciliation.
    -- Optional: NULL for non-cash sales, and NULL for cash too if the
    -- cashier didn't bother entering it.
    cash_received NUMERIC(15,3),
    change_given NUMERIC(15,3),
    -- One-time token generated fresh each time the POS page loads (see
    -- pos_page()/pos.html), submitted back with the checkout POST. A
    -- double-click ("Complete Sale" clicked twice on the same unchanged
    -- cart) previously created two separate, fully valid sales — no
    -- confirmation prompt either side, nothing tying the two submissions
    -- together. pos_checkout() checks for an existing sale with this key
    -- before inserting a new one; NULL for any sale that predates this
    -- column (never collides — see idx_sales_idempotency_key below).
    idempotency_key TEXT,
    -- "Clean Up" write-off — see the matching comment on billing.cleanup_amount.
    -- POS is single-shot (one sale, no repeat payments), so this is set
    -- once at checkout rather than accumulated across submissions.
    cleanup_amount NUMERIC(15,3) NOT NULL DEFAULT 0,
    cleanup_applied_by INTEGER,
    FOREIGN KEY (cashier_id) REFERENCES users(id),
    -- See F-19.
    FOREIGN KEY (discount_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (cleanup_applied_by) REFERENCES users(id) ON DELETE RESTRICT,
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (subtotal >= 0 AND subtotal <> 'NaN'),
    CHECK (total >= 0 AND total <> 'NaN'),
    CHECK (cleanup_amount >= 0 AND cleanup_amount <> 'NaN'),
    CHECK (cash_received IS NULL OR (cash_received >= 0 AND cash_received <> 'NaN')),
    CHECK (change_given IS NULL OR (change_given >= 0 AND change_given <> 'NaN')),
    CHECK (discount_percent BETWEEN 0 AND 100)
);
-- POS idempotency: a retried or double-clicked checkout carries the same
-- key, so it cannot record a second sale.
CREATE UNIQUE INDEX idx_sales_idempotency_key ON sales(idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX idx_sales_sold_at ON sales(sold_at);

CREATE TABLE sale_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_price NUMERIC(15,3) NOT NULL,
    line_total NUMERIC(15,3) NOT NULL,
    -- Cost snapshotted at sale time — this is what lets COGS reporting
    -- reflect the actual cost basis of each sale instead of re-reading
    -- current inventory cost (which would retroactively change a past
    -- month's COGS every time an item's cost is edited). Nullable: an
    -- item without a cost_price set has nothing to snapshot.
    unit_cost NUMERIC(15,3),
    -- Distributor snapshotted at sale time, alongside unit_cost above —
    -- this is what makes consignment_balance()'s attribution historically
    -- stable: re-pointing an item to a different distributor afterward
    -- (Inventory Catalog) no longer moves a past sale's cost with it.
    -- NULL for non-Consignment items and for sales that predate this
    -- column. See ORPHANED_RECORDS_AUDIT.md F-07.
    distributor_id INTEGER REFERENCES distributors(id),
    -- Was this line eligible for a discount when it was billed, copied
    -- from price_list.can_discount at insert. Snapshotted for the same
    -- reason unit_price is: can_discount can be edited at any time, and
    -- without the snapshot a later edit would silently change a past
    -- bill's total and misprice its refunds. NOT NULL with no default so
    -- a future insert site that forgets it fails loudly instead of
    -- silently marking a non-discountable item discountable.
    discountable BOOLEAN NOT NULL,
    FOREIGN KEY (sale_id) REFERENCES sales(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (quantity > 0 AND quantity <> 'NaN'),
    CHECK (unit_price >= 0 AND unit_price <> 'NaN'),
    CHECK (unit_cost IS NULL OR (unit_cost >= 0 AND unit_cost <> 'NaN')),
    CHECK (line_total >= 0 AND line_total <> 'NaN')
);
CREATE INDEX idx_saleitems_sale ON sale_items(sale_id);
CREATE INDEX idx_saleitems_item ON sale_items(item_id);

-- ============================================================ REFUNDS (Admin only)
-- Two kinds: 'retail' (one or more products returned, identified by barcode,
-- with an option to put the stock back) and 'service' (a straight revenue
-- reduction against a Visit or Inpatient case, no stock impact). Both reduce
-- revenue in the P&L for the month the refund itself was processed in —
-- not the original sale/visit's month — matching normal accounting practice.
CREATE TABLE refunds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_type TEXT NOT NULL CHECK (refund_type IN ('retail','service')),
    refund_date DATE NOT NULL,
    amount NUMERIC(15,3) NOT NULL,
    restocked BOOLEAN NOT NULL DEFAULT FALSE,   -- retail only: were the returned items put back into inventory?
    -- Retail only — which POS sale this refund is against. Required at
    -- the app layer (refund_retail_save() in app.py) so a retail refund
    -- can never be recorded against an item that was never actually
    -- sold, or for more than was sold minus what's already been
    -- refunded — see refund_items.sale_item_id for the per-line
    -- quantity/price tie-back.
    sale_id INTEGER,
    -- Service refunds anchor on exactly one of these three, mirroring
    -- payments.visit_id / inpatient_case_id / boarding_id. boarding_id was
    -- missing until 2026-09-10: money could be taken for a boarding stay
    -- (payments.boarding_id) and there was no way to give it back, because
    -- refunds_anchor_ck below required a visit or an inpatient case.
    visit_id INTEGER,                          -- service only
    inpatient_case_id INTEGER,              -- service only
    boarding_id INTEGER,                    -- service only
    reason TEXT,
    -- How the money was actually handed back — 'Cash', 'Card', or
    -- 'Transfer' (same vocabulary as sales.payment_method). Not
    -- necessarily the same method the original sale/payment used; Cash
    -- Register needs this to know which bucket to subtract a refund from.
    refund_method TEXT CHECK (refund_method IN ('Cash','Card','Transfer')),
    processed_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    -- Snapshot of the originating sale's/bill's cleanup_amount at the
    -- moment this refund was recorded — see CLEANUP_FEATURE_PLAN.md §4.5.
    -- Written once, not a live lookup, so this row stays self-contained
    -- even if the original bill's cleanup_amount changes afterward.
    cleanup_amount_at_refund NUMERIC(15,3) NOT NULL DEFAULT 0,
    -- A refund always reverses exactly one thing: a POS sale (retail), or
    -- one visit, one inpatient case, or one boarding stay (service). A
    -- goodwill/no-specific-record refund is handled through Cash Register
    -- instead, not this table. See ORPHANED_RECORDS_AUDIT.md F-05.
    CONSTRAINT refunds_anchor_ck CHECK (
        (refund_type = 'retail'  AND sale_id IS NOT NULL
            AND visit_id IS NULL AND inpatient_case_id IS NULL AND boarding_id IS NULL)
     OR (refund_type = 'service' AND sale_id IS NULL
            AND (visit_id IS NOT NULL)::int
              + (inpatient_case_id IS NOT NULL)::int
              + (boarding_id IS NOT NULL)::int = 1)
    ),
    FOREIGN KEY (sale_id) REFERENCES sales(id),
    FOREIGN KEY (visit_id) REFERENCES visits(id),
    FOREIGN KEY (inpatient_case_id) REFERENCES inpatient_cases(id),
    FOREIGN KEY (boarding_id) REFERENCES boarding_sessions(id),
    -- See F-19.
    FOREIGN KEY (processed_by) REFERENCES users(id) ON DELETE RESTRICT,
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (amount >= 0 AND amount <> 'NaN'),
    CHECK (cleanup_amount_at_refund >= 0 AND cleanup_amount_at_refund <> 'NaN')
);
CREATE INDEX idx_refunds_date ON refunds(refund_date);
CREATE INDEX idx_refunds_sale ON refunds(sale_id);
CREATE INDEX idx_refunds_visit ON refunds(visit_id);
CREATE INDEX idx_refunds_case ON refunds(inpatient_case_id);
CREATE INDEX idx_refunds_boarding ON refunds(boarding_id);

CREATE TABLE refund_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refund_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    quantity NUMERIC(10,3) NOT NULL,
    unit_price NUMERIC(15,3) NOT NULL,
    line_total NUMERIC(15,3) NOT NULL,
    -- The specific sale_items row this line is refunding against — lets
    -- refund_retail_save() price from what was actually charged (not
    -- today's Price List price) and sum prior refunds against this exact
    -- line to enforce a refund can never exceed what was actually sold.
    -- Never NULL: the P&L and consignment_balance() reverse a restock at
    -- the cost and distributor the SALE LINE carried (audit B9).
    sale_item_id INTEGER NOT NULL,
    FOREIGN KEY (refund_id) REFERENCES refunds(id),
    FOREIGN KEY (item_id) REFERENCES inventory_list(id),
    FOREIGN KEY (sale_item_id) REFERENCES sale_items(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (quantity > 0 AND quantity <> 'NaN'),
    CHECK (unit_price >= 0 AND unit_price <> 'NaN'),
    CHECK (line_total >= 0 AND line_total <> 'NaN')
);
CREATE INDEX idx_refunditems_refund ON refund_items(refund_id);
CREATE INDEX idx_refunditems_saleitem ON refund_items(sale_item_id);

-- ============================================================ CASH REGISTER
-- Unifies every place money actually changes hands on a given day (POS
-- sales, Visit/Inpatient/Boarding payments, and refunds netted as
-- negative) for end-of-day cash-up against what's physically in the till.
CREATE TABLE cash_register_payouts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payout_date DATE NOT NULL,
    amount NUMERIC(15,3) NOT NULL,
    reason TEXT NOT NULL,
    logged_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (logged_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (amount > 0 AND amount <> 'NaN')
);
CREATE INDEX idx_cashpayouts_date ON cash_register_payouts(payout_date);

-- One immutable historical entry per audit — a re-audit of the same day
-- adds a new row rather than overwriting the old one.
CREATE TABLE cash_register_audits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_date DATE NOT NULL,
    system_cash NUMERIC(15,3) NOT NULL,
    system_card NUMERIC(15,3) NOT NULL,
    system_transfer NUMERIC(15,3) NOT NULL,
    counted_cash NUMERIC(15,3) NOT NULL,
    difference NUMERIC(15,3) NOT NULL,      -- counted_cash - system_cash
    status TEXT NOT NULL CHECK (status IN ('Deficit','Surplus','Perfect')),
    notes TEXT,
    performed_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (performed_by) REFERENCES users(id),
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (counted_cash >= 0 AND counted_cash <> 'NaN'),
    CHECK (system_cash <> 'NaN'),
    CHECK (system_card <> 'NaN'),
    CHECK (system_transfer <> 'NaN'),
    CHECK (difference <> 'NaN')
);
CREATE INDEX idx_cashaudits_date ON cash_register_audits(audit_date);

-- ============================================================ OPEX / P&L (monthly is the source; yearly rolls it up)
CREATE TABLE monthly_opex (
    month TEXT PRIMARY KEY,           -- 'YYYY-MM'
    rent NUMERIC(15,3) NOT NULL DEFAULT 0,
    salaries NUMERIC(15,3) NOT NULL DEFAULT 0,
    utilities NUMERIC(15,3) NOT NULL DEFAULT 0,
    marketing NUMERIC(15,3) NOT NULL DEFAULT 0,
    other NUMERIC(15,3) NOT NULL DEFAULT 0,
    -- Amounts: never NaN (Postgres sorts NaN above every number, so a
    -- plain `>= 0` passes it), and never below what the routes allow.
    CHECK (rent >= 0 AND rent <> 'NaN'),
    CHECK (salaries >= 0 AND salaries <> 'NaN'),
    CHECK (utilities >= 0 AND utilities <> 'NaN'),
    CHECK (marketing >= 0 AND marketing <> 'NaN'),
    CHECK (other >= 0 AND other <> 'NaN')
);


-- ============================================================ APPOINTMENTS
-- Slot grid is generated dynamically from settings (appt_start_time / appt_end_time /
-- appt_slot_minutes) — no fixed slot table needed; slot labels (each slot's own start
-- time, e.g. '09:00', '09:30'...) are derived at render time from that range.
CREATE TABLE appointments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appt_date DATE NOT NULL,
    slot_label TEXT NOT NULL,          -- the slot's start time, e.g. '09:00', '09:30'...
    resource_type TEXT NOT NULL CHECK (resource_type IN ('vet','grooming')),
    resource_id INTEGER,                  -- users.id when resource_type='vet'; NULL for grooming
    pet_name TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    appointment_type TEXT NOT NULL CHECK (appointment_type IN ('Medical','Grooming')),
    reason TEXT,
    created_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    -- resource_id is the one that already demonstrably orphans —
    -- logic.orphaned_appointments() exists precisely because this
    -- reference can stop resolving. See F-19.
    FOREIGN KEY (resource_id) REFERENCES users(id) ON DELETE RESTRICT,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
);
CREATE INDEX idx_appt_date ON appointments(appt_date);

-- Enforces at the database level what logic.slot_conflict() only checks at
-- the application level: two appointments can't occupy the same slot for
-- the same vet/groomer. The app-level check-then-insert alone has a race
-- window — two concurrent bookings for the same slot can both pass the
-- check before either inserts. COALESCE(resource_id, 0) is needed because
-- resource_id is NULL for grooming rows, and Postgres otherwise treats
-- every NULL as distinct (so two grooming rows for the same slot would
-- never actually collide on a plain (appt_date, slot_label, resource_type,
-- resource_id) unique index).
CREATE UNIQUE INDEX uq_appointments_slot
    ON appointments (appt_date, slot_label, resource_type, COALESCE(resource_id, 0));


-- Layer 1 of operational monitoring: one row per self-check run.
-- reported_at is set by heartbeat.py once that result has been sent; NULL
-- means it has not been (or the heartbeat is disabled, which is the
-- default). Pruned to 180 rows by selfcheck.record().
CREATE TABLE self_check_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ran_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('ok','warn','fail')),
    findings TEXT,
    reported_at TIMESTAMPTZ
);
CREATE INDEX idx_selfcheck_ran ON self_check_log(ran_at DESC);
